### ISSUE TITLE
tuyaface.tuyaclient will always result in True

### ISSUE THREAD

**Issue by kart-able** [TradeFace/tuyaface#83]
Changing 1 for 0 in `client.set_state(!data['dps']['1'], 1) #toggle` should give False, I suppose.

Removed the ! before data because it resulted in an error  (but I'm a complete noob in python).

**Comment by TradeFace** [comment]
From which code base did you get `client.set_state(!data['dps']['1'], 1) #toggle`? I don't recognize that line.

**Comment by kart-able** [comment]
From your example:

`from tuyaface.tuyaclient import TuyaClient

def on_status(data: dict):
    print(data)

def on_connection(value: bool):
    print(value)

device = {
    'protocol': '3.3', # 3.1 | 3.3
    'deviceid': '34280100600194d17c96',
    'localkey': 'e7e9339aa82abe61',
    'ip': '192.168.1.101',            
}

client = TuyaClient(device, on_status, on_connection)
client.start()

data = client.status()
client.set_state(!data['dps']['1'], 1) #toggle
client.stop_client()`

**Comment by TradeFace** [comment]
Provide that your device has a dps with key 1, the example should be correct. Add a print statement to your test to see which values data holds. 

Their is already a implementation available, mostly focused on HA https://github.com/TradeFace/tuyagateway. Maybe that saves you some time.

**Comment by kart-able** [comment]
Hi,

As I said, I am a noob in python and I don't know where to place a print
statement as you suggest.

I am indeed very much interested in Tuyagateway and Gismocaster.
I installed Gismocaster in Home Assistant, but i could not go further
because of a login page:
https://community.home-assistant.io/t/tuyagateway-v2-0-now-available/204092/167

Rgds

Le jeu. 24 sept. 2020 à 18:43, TradeFace <notifications@github.com> a
écrit :

**Comment by TradeFace** [comment]
login for GC is admin:admin as described in the doc. Anyways if you are a noob in python perhaps it is better to first get a basic understanding of python before venturing off writing a tuyaface implementation.

**Comment by kart-able** [comment]
All I am looking for is a (simple) solution for a Tuya 1 gang switch and if Tuyaface doesn't work, it's perhaps bad news for Gismocaster in Home Assistant. 

I am also trying with Openhab and it's like using a hammer to kill a fly. This switch cannot be tasmotized as there is no ESP inside. The only thing that works apart from the Tuya app is Tuyapi, only for switching on, but not off. That's why I had some hope in Tuyaface.

**Comment by TradeFace** [comment]
Uhmm ? I run 20+ tuya switches with TG / GC... so something must be working with tuyaface.  But yes TG / GC are not the most user friendly at the moment... it is not recommend for non developers atm.
