### ISSUE TITLE
Question about how to get localkey without Tuya IoT Platform❓ 

### ISSUE THREAD

**Issue by fajarmnrozaki** [TradeFace/tuyaface#87]
May I ask how to get or generate "localkey" of Tuya Device without connecting to Tuya IoT Platform?

example :
device = {
    'protocol': '3.3', # 3.1 | 3.3
    'deviceid': '34280100600194d17c96',
    'localkey': 'e7e9339aa82abe61',
    'ip': '192.168.1.101',            
}

**Comment by ogr0** [comment]
https://youtu.be/Q1ZShFJDvE0 solved!

**Comment by fajarmnrozaki** [comment]
Thank you for the answer.
